apiVersion: v1
kind: Service
metadata:
  labels:
    serve: hook
  name: admission-webhook
  namespace: default
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    serve: hook
  sessionAffinity: None
  type: ClusterIP
