apiVersion: v1
kind: Pod
metadata:
  name: webhook-to-be-mutated
spec:
  containers:
    - name: mutating-pod
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "while :; do  sleep 5 ; done" ]